// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVFG749feOg2qAS1Ge0zkcQVBkZCk9o_I',
    appId: '1:352128566046:android:9bc1eec77b14f78a66bf0f',
    messagingSenderId: '352128566046',
    projectId: 'latest-news-1',
    storageBucket: 'latest-news-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1idgQZUMP8ug-sT2tEDhYSjrr2Zj2MbM',
    appId: '1:352128566046:ios:dd11248b3b4fa9e666bf0f',
    messagingSenderId: '352128566046',
    projectId: 'latest-news-1',
    storageBucket: 'latest-news-1.appspot.com',
    androidClientId: '352128566046-ip8g8athego0g2ku17jjp9o9bl5pif1o.apps.googleusercontent.com',
    iosClientId: '352128566046-e0ljt4dcc69qs0kv7kb9q32f58k1un23.apps.googleusercontent.com',
    iosBundleId: 'zfani.assaf.news',
  );
}
